# Generated by Django 5.2.7 on 2025-10-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="estilo_favorito",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="perfil",
            name="tamanho_roupa",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
