# Generated by Django 5.2.7 on 2025-12-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0002_perfil_estilo_favorito_perfil_tamanho_roupa"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnifiedFashionStyle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_column="NAME", max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, db_column="SLUG", max_length=255, unique=True
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True, db_column="SHORT_DESC", max_length=512
                    ),
                ),
                ("history", models.TextField(blank=True, db_column="HISTORY")),
                (
                    "countries",
                    models.JSONField(blank=True, db_column="COUNTRIES", default=list),
                ),
                (
                    "celebrities",
                    models.JSONField(blank=True, db_column="CELEBRITIES", default=list),
                ),
                (
                    "products",
                    models.JSONField(blank=True, db_column="PRODUCTS", default=list),
                ),
                (
                    "orders",
                    models.JSONField(blank=True, db_column="ORDERS", default=list),
                ),
                ("featured", models.BooleanField(db_column="FEATURED", default=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="CREATED_AT"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="UPDATED_AT"),
                ),
            ],
            options={
                "db_table": "UnifiedFashionStyle",
                "ordering": ["name"],
                "managed": True,
            },
        ),
    ]
